### ISSUE TITLE
Tabular Data Category : pytorch-tabnet

### ISSUE THREAD

**Issue by Optimox** [ritchieng/the-incredible-pytorch#102]
To my surprise there is no tabular data category in the list, while it’s probably the most common type of data you encounter in Machine Learning.

I would suggest adding pytorch-tabnet to the newly created « Tabular Data » category. Pytorch-tabnet allows easy training of TabNet model (attention based model for tabular data) for binary/multi-class classification, regression and multi-target regression.

Hope you’ll like the repo and share the love!

https://github.com/dreamquark-ai/tabnet

Thanks!

**Comment by ritchieng** [comment]
Indeed, this is an important segment. Would you like to make a pull request? I'll approve it!

**Comment by Optimox** [comment]
@ritchieng I made the corresponding PR, let me know if it’s not ok.

**Comment by ritchieng** [comment]
Merged! Thanks 😃
