### ISSUE TITLE
Privacy preserving machine learning category

### ISSUE THREAD

**Issue by Boluwatifeh** [ritchieng/the-incredible-pytorch#117]
Let's add a category with papers, tutorials and notebooks on privacy preserving ML leveraging pytorch

**Comment by Boluwatifeh** [comment]
Working on this, i would make a PR as soon as I'm done

**Comment by ritchieng** [comment]
Yes that's a useful category. For now, only code repositories thanks :)

**Comment by Boluwatifeh** [comment]
Okay, closing the issue.

**Comment by Boluwatifeh** [comment]
Ohh, i misunderstood your reply
