### ISSUE TITLE
Image Captioning paper

### ISSUE THREAD

**Issue by AnukritiSinghh** [ritchieng/the-incredible-pytorch#118]
Hello, 
Thanks for the amazing collection. 
But I would like to point out one thing - in the image captioning topic there are three mentioned papers which are correct if we see the captioning field but since this collection is about pytorch I was confuse why the 'DenceCap' paper is there because the paper is on lua, lua with torch.

**Comment by ritchieng** [comment]
Yes, you're right. That particular link is wrong for DenseCap, we should remove it. Would you like to do a pull request?

**Comment by AnukritiSinghh** [comment]
Yeah, I would like to make a PR, I will replace it with a newer link of dense captioning.

**Comment by ritchieng** [comment]
Thank you! A stable one would be by salesforce team. You can update to that.

https://github.com/salesforce/densecap

**Comment by AnukritiSinghh** [comment]
That is a wonderful paper but I didn't go for it here because your topic
specifically mentions 'image' captioning and the salesforce one is for
videos.
I created a PR, please check it out and let me know if that paper is
alright.

Thanks,
Anukriti

**Comment by ritchieng** [comment]
Ok, waiting on your pull request. Yet to see it! 👍

**Comment by ritchieng** [comment]
Merged! Thank you :)
