### ISSUE TITLE
Continual learning in pytorch

### ISSUE THREAD

**Issue by 610v4nn1** [ritchieng/the-incredible-pytorch#133]
We created Renate, a library for continual learning algorithms: https://github.com/awslabs/renate
I didn't open a PR since there is not specific category for that.

**Comment by ritchieng** [comment]
Cool! I will create a new category.

**Comment by ritchieng** [comment]
Done, created a new category and added Renate. Thank you, will be trying this out too.

https://github.com/ritchieng/the-incredible-pytorch/commit/d5d3087779bf68c70c121ebc60d2861af61e5da9

**Comment by 610v4nn1** [comment]
Cool! Thanks.
