### ISSUE TITLE
implementation of DNI

### ISSUE THREAD

**Issue by andrewliao11** [ritchieng/the-incredible-pytorch#21]
hi @ritchieng, 
I just implement [Decoupled Neural Interfaces using Synthetic Gradients](https://arxiv.org/abs/1608.05343) in pytorch, [here](https://github.com/andrewliao11/dni.pytorch)
May add it 👍

**Comment by ritchieng** [comment]
Done :) 

Commit: https://github.com/ritchieng/the-incredible-pytorch/commit/4b2b7681aed85d3185bca352f096f02d42054279

Gloqo: https://www.gloqo.com/t/decoupled-neural-interfaces-using-synthetic-gradients-python-pytorch/190
