### ISSUE TITLE
Feature request - addition timestamp

### ISSUE THREAD

**Issue by rosenfeldamir** [ritchieng/the-incredible-pytorch#22]
Hi, this is a wonderful repository!
Is there an option to put a date near each addition, or somehow make it so I can tell which ones were added most recently? I know I can look at the chance log but that's rather cumbersome.

**Comment by ritchieng** [comment]
@rosenfeldamir All new additions are added to the end of each list which is cleaner than putting dates :) Also, you can head to [https://www.gloqo.com/](https://www.gloqo.com/) where you can view latest additions (paper implementations only).
