### ISSUE TITLE
Another implementation of Hierarchical Attention Network for Document classification.

### ISSUE THREAD

**Issue by cedias** [ritchieng/the-incredible-pytorch#38]
Hi,
I did another implementation of Hierarchical Attention Network for Document classification ([HAN-Pytorch](https://github.com/cedias/HAN-pytorch)). Not sure how to add it as there is already one, i'll let you choose how to do it.

Cheers,
Charles.

**Comment by ritchieng** [comment]
Done: https://github.com/ritchieng/the-incredible-pytorch/commit/26c4f767cca874548383480bd97223068d3eec57
