### ISSUE TITLE
adding torchsample

### ISSUE THREAD

**Issue by ncullen93** [ritchieng/the-incredible-pytorch#4]
Hi @ritchieng , Was hoping you can add my new package - `torchsample` - to this list. It includes a lot of transforms and data samplers which significantly extend the current functionality in torch/torchvision.

https://github.com/ncullen93/torchsample

Thanks!

**Comment by ritchieng** [comment]
Done! Commit: https://github.com/ritchieng/the-incredible-pytorch/commit/1725be7928660073505ccf791dd8c7602374e4cd
