### ISSUE TITLE
Unsupervised Learning of Depth and Ego-Motion from Video was not originally implemented in pytorch

### ISSUE THREAD

**Issue by ClementPinard** [ritchieng/the-incredible-pytorch#42]
Hello, thanks a lot for your nice repo !

You introduced the paper "Unsupervised Learning of Depth and Ego-Motion from Video" and the implementation I've done (https://github.com/ClementPinard/SfmLearner-Pytorch) as "Papers Originally Implemented with PyTorch" , but the original implementation is in Tensorflow, made by [tinghuiz](https://github.com/tinghuiz) : https://github.com/tinghuiz/SfMLearner

**Comment by ritchieng** [comment]
Will change this, thanks for the heads up!

**Comment by ritchieng** [comment]
Done: https://github.com/ritchieng/the-incredible-pytorch/commit/26c4f767cca874548383480bd97223068d3eec57
