### ISSUE TITLE
Sequence Labeling models (LSTM-CRF with character LSTM/CNN features)

### ISSUE THREAD

**Issue by jiesutd** [ritchieng/the-incredible-pytorch#46]
Hi,

I have implemented a PyTorch based Sequence Labeling framework. [PyTorchSeqLabel](https://github.com/jiesutd/PyTorchSeqLabel)

It is a LSTM-CRF structure with a choice of character LSTM/CNN features input.

This repository reimplements structures in following two papers:
1. Neural Architectures for Named Entity Recognition, NAACL2016
2. End-to-end Sequence Labeling via Bi-directional LSTM-CNNs-CRF, ACL2016

**Comment by ritchieng** [comment]
Done :)

https://github.com/ritchieng/the-incredible-pytorch/commit/e4aea6d0500ffb199ff15facbb1ee3d2b0e546f1
