### ISSUE TITLE
Include yunjey pytorch tutorial

### ISSUE THREAD

**Issue by obust** [ritchieng/the-incredible-pytorch#8]
I think the incredible pytorch would benefit from referencing this well written tutorial on pytorch
https://github.com/yunjey/pytorch-tutorial

**Comment by ritchieng** [comment]
Yeah this is incredible. Will be adding it.

**Comment by ritchieng** [comment]
Done: https://github.com/ritchieng/the-incredible-pytorch/commit/bfa60ea4a8b8b7aa12b835a88cc9195b76be49cc
