### ISSUE TITLE
Consider adding MedicalZoo Pytorch

### ISSUE THREAD

**Issue by black0017** [ritchieng/the-incredible-pytorch#94]
Hello, would you please consider adding MedicalZoo Pytorch  in the medical section?
It is a deep learning framework for multi-modal 2D/3D medical image segmentation.

Link: https://github.com/black0017/MedicalZooPytorch

Great work by the way!

N.A.

**Comment by ritchieng** [comment]
Done! :) Very useful library.

https://github.com/ritchieng/the-incredible-pytorch/commit/97de767e13c718e921ff69041df8ae8b6ca245c7
